### PR TITLE
 Updates docker with entrypoint script setup

### PR DESCRIPTION
**Pull request by m038**
- Installs composer dependencies automatically
  - Chowns all command by user on each run
  - Also makes a volume in php-fpm container with web dir

### CODE REVIEW

**Comment by takeit** [comment]
I would hold on with it, I found there some issues. First  of all there is no curl, volumes are not configured properly which actually doesnt mount the host repo to the container repo, it would be better to create a sepearate Dockerfile config for the renderer and separate things from each other

**Comment by ahilles107** [comment]
@takeit - can you explain more?

**Comment by m038** [comment]
Curl is added to the list of packages to install.

**Comment by takeit** [comment]
in the entrypoint file there is installation of the composer using curl, curl is not defined to be installed in the Dockerfile, thus it fails due to missing bin file. Also mapping the volumes is incosistent (but that was introduced in previous PRs). Volumes for the symofny app are defined in the nginx dockerfile - this needs to be done preferably in a separate Dockerfile that will run commands related only to the symfony code and not to the php and nginx

**Comment by ahilles107** [comment]
Yeah, it can be in separate docker - not the nginx one - it was like this on beginning but i wanted to check if performance of docker will be better with just two images instead 3. But looks like on mac boot2docker is an issue.

**Comment by ahilles107** [comment]
@m038 - can you move nginx to seperate container?

**Comment by m038** [comment]
@ahilles107 i think @takeit was already working on this. Let's wait for his PR.

**Comment by takeit** [comment]
please, don't wait for me, had some issues with the docker config for separate container. Seems it needs more time to investigate. As for now, this can be merged.

**Pull request merged**
